---
- name: Test HTTP Output
  hosts: "{{ target_host_name }}*"
  gather_facts: yes

  vars:
    website_ip: "http://{{ ansible_ip_addresses[0] }}"
    ports:
      - 8080
      - 8081
  
  tasks:
  - name: check HTTP status 200 from GET
    win_uri:
      url: "{{ website_ip }}:{{ item }}"
    with_items: "{{ ports }}"

  - name: check if the word Ansible for Everyone is in the page contents
    win_uri:
      url: "{{ website_ip }}:{{ item }}"
      return_content: yes
    register: weboutput1
    failed_when: "'Automation for Everyone' not in weboutput1.content"
    with_items: "{{ ports }}"

  - name: check if the word Ansible Workshops is in the page contents
    win_uri:
      url: "{{ website_ip }}:{{ item }}"
      return_content: yes
    register: weboutput2
    failed_when: "'Automation for Everyone' not in weboutput2.content"
    with_items: "{{ ports }}"
...
