---
- name: Windows Server Create AD User
  hosts: "{{ target_host_name }}*"

  # The variables will be taken from Tower Survey
  # always required: 
  # - domain_group_name : e.g. staff, manager, accounting
  # - ad_user_name : e.g. bob, john, michael
  # - ad_user_state : present/absent
  # required for new addition
  # - ad_user_firstname
  # - ad_user_surname
  # - ad_user_password
  # - ad_user_email
  tasks:
  - name: ensure domain group is present
    win_domain_group:
      name: "{{ domain_group_name }}"
      scope: global
      state: present

  - name: create/delete simple domain user 
    win_domain_user:
      name: "{{ ad_user_name }}"
      firstname: "{{ ad_user_firstname }}"
      surname: "{{ ad_user_surname }}"
      password: "{{ ad_user_password }}"
      email: "{{ ad_user_email }}"
      state: "{{ ad_user_state }}"

  - name: add a domain user to a domain group on creation
    win_domain_group_membership:
      name: "{{ domain_group_name }}"
      members:
        - "{{ ad_user_name }}"
      state: "{{ ad_user_state }}"
      when: ad_user_state == present
...