---
- name: Windows Remove Software Demo
  hosts: "{{ target_host_name }}*"

  tasks:
  - name: remove software using Chocolatey.org
    win_chocolatey:
      name: "{{ software_name }}"
      state: absent
