---
- name: Test HTTP Output
  hosts: "{{ target_host_name }}*"
  gather_facts: yes

  vars:
    - website_ip: "{{ ansible_ip_addresses[0] }}"
  
  tasks:
  - name: check HTTP status 200 from GET
    win_uri:
      url: "http://{{ website_ip }}"

  - name: check if the word Ansible for Everyone is in the page contents
    win_uri:
      url: "http://{{ website_ip }}"
      return_content: yes
    register: weboutput1
    failed_when: "'Automation for Everyone' not in weboutput1.content"

  - name: check if the word Ansible Workshops is in the page contents
    win_uri:
      url: "http://{{ website_ip }}"
      return_content: yes
    register: weboutput2
    failed_when: "'Automation for Everyone' not in weboutput2.content"
...
