---
- name: Windows Patch - Hotfix
  hosts: "{{ target_host_name }}*"

  tasks: 
  - name: Install hotfix {{ hotfix_kb }}
    win_hotfix:
      hotfix_kb: "{{ hotfix_kb }}"
    register: hotfix_install

  - win_reboot:
    when: hotfix_install.reboot_required  
...