---
- name: Playbook to Install IIS Server
  hosts: "{{ target_host_name }}*"

  vars:
    iis_sites:
      - name: 'Ansible Website 1'
        port: '8080'
        path: 'C:\sites\website1'
        indexfile: 'index-website-1.html.j2'
      - name: 'Ansible Website 2'
        port: '8081'
        path: 'C:\sites\website2'
        indexfile: 'index-website-2.html.j2'
    iis_test_message: "Hello World!  My test IIS Server created by Ansible"

  tasks:
  - name: Install IIS
    win_feature:
      name: Web-Server
      state: present

  - name: Create site directory structure
    win_file:
      path: "{{ item.path }}"
      state: directory
    with_items: "{{ iis_sites }}"

  - name: Create IIS site
    win_iis_website:
      name: "{{ item.name }}"
      state: started
      port: "{{ item.port }}"
      physical_path: "{{ item.path }}"
    with_items: "{{ iis_sites }}"
    notify: restart iis service

  - name: Open port for site on the firewall
    win_firewall_rule:
      name: "iisport{{ item.port }}"
      enable: yes
      state: present
      localport: "{{ item.port }}"
      action: Allow
      direction: In
      protocol: Tcp
    with_items: "{{ iis_sites }}"

  - name: Template simple web site to iis_site_path as index.html
    win_template:
      src: 'templates/{{ item.indexfile }}'
      dest: '{{ item.path }}\index.html'
    with_items: "{{ iis_sites }}"

  - name: copy the rest of html files
    win_copy:
      src: "templates/static/"
      dest: "{{ item.path }}"
    with_items: "{{ iis_sites }}"  

  handlers:
    - name: restart iis service
      win_service:
        name: W3Svc
        state: restarted
        start_mode: auto
...
