---
- name: Windows Server File Sharing Permission
  hosts: "{{ target_host_name }}*"

  vars:
  - share_full: " "
  - share_read: " "
  - share_deny: " "

  tasks:
  - name: ensure share directory is present
    win_file:
      path: "{{ share_path }}"
      state: directory

  - name: modify directory sharing
    win_share:
      name: "{{ share_name }}"
      description: "{{ share_description }}"
      list: "{{ share_file_list }}"
      full: "{{ share_full }}"
      read: "{{ share_read }}"
      deny: "{{ share_deny }}"

  # Example
  #- name: Add secret share
  #  win_share:
  #    name: internal
  #    description: top secret share
  #    path: C:\shares\internal
  #    list: no
  #    full: FKARNADI\Administrator,FKARNADI\feliz
  #    read: FKARNADI\jono
  #    deny: FKARNADI\steve
...