---
- name: Windows Install Software Demo
  hosts: "{{ target_host_name }}*"

  tasks:
  # Install/Update Software using Chocolatey.org package manager
  # Chocolatey is going to be auto-installed if not present
  # See https://chocolatey.org/packages for complete package list  
  - name: install software using Chocolatey.org
    win_chocolatey:
      name: "{{ software_name }}"
      state: latest

  